METS-Programme/openmrs-module-ugandaemr-reports

.travis.yml, api/src/main/java/org/openmrs/module/ugandaemrreports/activator/ReportInitializer.java, api/src/main/java/org/openmrs/module/ugandaemrreports/library/DataFactory.java, api/src/main/java/org/openmrs/module/ugandaemrreports/library/HIVCohortDefinitionLibrary.java
This removes caching and speeds up development and testing of the reports
=> Quick fix to redeploy all changes to reports on restart 

.travis.yml
This approach is officially recommended by travis-ci at https://blog.travis-ci.com/2017-03-30-deploy-maven-travis-ci-packagecloud/
=> Copying settings.xml instead of providing via a param

api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupARTRegister.java, omod/src/main/resources/apps/ugandaemr_reports_app.json
I have implemented the functionality for exporting the ART Register as a CSV, the link to the card is here by attached 
https://trello.com/c/eL5SRoOP/716-make-the-art-register-exportable-as-csv
=> ART Register exportable as CSV

api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupANCRegister.java
@ssmusoke and @balukujr please find here the PR for exporting the ANC register as a csv file, waiting for your reviews. Thank you...
=> ANC Register Export as CSV

api/src/main/java/org/openmrs/module/ugandaemrreports/definition/cohort/definition/PatientsWhoDidntTurnupForScheduledAppointmentCohortDefinition.java, api/src/main/java/org/openmrs/module/ugandaemrreports/definition/cohort/evaluator/DSDMCohortDefinitionEvaluator.java, api/src/main/java/org/openmrs/module/ugandaemrreports/definition/cohort/evaluator/PatientsWhoDidntTurnupForScheduledAppointmentCohortDefinitionEvaluator.java, api/src/main/java/org/openmrs/module/ugandaemrreports/library/DataFactory.java
https://trello.com/c/cGo8GOAp
Excluded early_bird patients who come earlier than the expected visit date and renamed cohort.
=> Excluded early_bird patients who come earlier than the expected visit date and renamed the cohort 

api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetUpEWILostToFollowUp.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetUpLostReport.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetUpLostToFollowUp.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetUpStabilityAssessmentReport.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/Setup106A1ADSDMReport.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/Setup106A1AReport.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupARTRegister.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupActiveOnCareList.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupAdherenceReport.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupAppointmentList.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupDeathList.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupDueForViralLoad.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupEIDRegister.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupEWIPillPickupReport.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupEWIViralLoadSupressionReport.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupHMIS053PatientAppointmentBook.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupInfantDueForAppointment.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupInfantDueForFirstPCR.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupInfantDueForRapidTest.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupInfantDueForSecondPCR.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupMissedAppointmentList.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupOverDueForViralLoadReport.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupPMTCTSTATReport.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupTransferInList.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupTransferOutList.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupTxCurrent_30DaysReport.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupTxCurrent_90DaysReport.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupTxNewReport.java
https://app.asana.com/0/0/1119825446353802/f
=> Added description To the Reports to describe what they entail

api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupHCTRegister.java
This is a PR for the ticket: https://app.asana.com/0/1116983304078777/1122794302487398
=> Add CSV data export for the HTC Register

api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetUpRecencyHTSClientCardDataExportReport2019.java, omod/src/main/resources/apps/ugandaemr_reports_app.json
Added Recency HTS Client Card Data Export Report
=> recencyHTSClientCardReport

omod/src/main/resources/apps/ugandaemr_reports_app.json, omod/src/main/resources/config.xml
https://app.asana.com/0/1133167201254913/1149123840716105
=> Adding privileges to reporting

api/src/main/java/org/openmrs/module/ugandaemrreports/reports2019/SetupPNCRegister2019.java
Add the Father's Name to the PNC Report
=> Add Father's Name to PNC

api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupANCRegister.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupActiveOnCareList.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupHTSRegister2019.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupMaternityRegister.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports2019/SetupPNCRegister2019.java
The ticket is here: https://app.asana.com/0/1133167201254915/1163465995915835
=> Add a generic Method for CSV Design UUId

omod/src/main/resources/apps/ugandaemr_reports_app.json, omod/src/main/webapp/pages/reports.gsp, omod/src/main/webapp/pages/reports_2014.gsp
https://app.asana.com/0/1133167201254915/1174689412717417
=> Add Missing Reports

api/src/main/java/org/openmrs/module/ugandaemrreports/data/converter/CodedConceptUUIDValueConverter.java, api/src/main/java/org/openmrs/module/ugandaemrreports/definition/data/definition/PersonUUIDDataDefinition.java, api/src/main/java/org/openmrs/module/ugandaemrreports/definition/data/evaluator/PatientUUIDDefinitionEvaluator.java, api/src/main/java/org/openmrs/module/ugandaemrreports/library/DataFactory.java, api/src/main/java/org/openmrs/module/ugandaemrreports/library/HIVPatientDataLibrary.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetUpMobileAppointmentLists.java
https://app.asana.com/0/1133167201254915/1189844299818201
=> Add Regimen UUID and Patient UUID to the Appointment List

api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupMERTxNew2019Report.java
https://app.asana.com/0/1188443031575715/1189683635147809/f
=> Excluding  Transferred In patients  from TX_new

api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetUpNonSuppressedClientsReport.java
https://app.asana.com/0/1133167201254915/1185977732524357/f
=> NonSuppressed Viral Load Facility Report fix

api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetUpMobileAppointmentLists.java
https://app.asana.com/0/1133167201254915/1194086587312929
=>  Add Missed Appointment records to the Mobile Appointments List

api/src/main/java/org/openmrs/module/ugandaemrreports/library/DataFactory.java, api/src/main/java/org/openmrs/module/ugandaemrreports/library/HIVCohortDefinitionLibrary.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupActiveOnCareList.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupTxCurrent_28Days2019Report.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupTxCurrent_90Days2019Report.java
https://app.asana.com/0/1133167201254913/1188184047451841/f
=> Improved Cohorts for TX CURR Report

api/src/main/java/org/openmrs/module/ugandaemrreports/library/HIVCohortDefinitionLibrary.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports2019/SetupMER_TX_ML2019Report.java
https://app.asana.com/0/1133167201254915/1199139247803477/f
=> Revised TXML Cohort to ensure the clients are lost to follow up within the period

api/src/main/java/org/openmrs/module/ugandaemrreports/definition/dataset/evaluator/EMRVersionDatasetEvaluator.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reporting/dataset/definition/SharedDataDefintion.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupAnalyticsMetricReport.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupEWIPillPickupReport.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupEWIViralLoadSupressionReport.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupPediatricDataCallReport.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupSMCRegister.java
https://app.asana.com/0/1133167201254913/1200231553003863/f
=> FIX R.build.info error in analiytics_data

api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetUpClientsTransitionedToDTGReport.java
https://app.asana.com/0/1133167201254915/1199219808799536/f
=> Exempting patients started on DTG from the report cohort

api/src/main/java/org/openmrs/module/ugandaemrreports/library/HIVCohortDefinitionLibrary.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetUpLostReport.java
https://app.asana.com/0/1133167201254915/1200110841480654/f
=> Lost_Clients_Reports_Cohort_Revision

api/src/main/java/org/openmrs/module/ugandaemrreports/metadata/HIVMetadata.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupAnalyticsMetricReport.java, api/src/main/resources/org/openmrs/module/ugandaemrreports/reports/METRICS.json
https://app.asana.com/0/1133167201254915/1200414606407111/f
=> Update the EMR Analytics 

api/src/main/java/org/openmrs/module/ugandaemrreports/library/DataFactory.java, api/src/main/java/org/openmrs/module/ugandaemrreports/library/HIVCohortDefinitionLibrary.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports2019/SetupTxRTT2019Report.java
https://app.asana.com/0/1133167201254913/1200548368430126
=> Revising the MER TX_RTT Report 

api/src/main/java/org/openmrs/module/ugandaemrreports/library/HIVCohortDefinitionLibrary.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetUpLostReport.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetUpLostToFollowUp.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupActiveOnCareList.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupPEPFARActiveOnCareList.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupTxCurrent_28Days2019Report.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupTxCurrent_90Days2019Report.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports2019/Setup106A1A2019Report.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports2019/Setup106A1A2019SectionsHC16ToHC28Report.java
https://app.asana.com/0/1133167201254913/1200563958294073/f
=> Revising lost and LTFP cohorts to add clients that overlap reporting quarters

api/src/main/java/org/openmrs/module/ugandaemrreports/definition/cohort/definition/AppointmentDateAtLocationCohortDefinition.java, api/src/main/java/org/openmrs/module/ugandaemrreports/definition/cohort/evaluator/AppointmentDateAtLocationCohortDefinitionEvaluator.java, api/src/main/java/org/openmrs/module/ugandaemrreports/definition/data/definition/ReturnVisitDatePatientDataDefinition.java, api/src/main/java/org/openmrs/module/ugandaemrreports/definition/data/evaluator/ReturnVisitDatePatientDataEvaluator.java, api/src/main/java/org/openmrs/module/ugandaemrreports/library/DataFactory.java, api/src/main/java/org/openmrs/module/ugandaemrreports/library/HIVPatientDataLibrary.java, api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetupAppointmentList.java
https://app.asana.com/0/1133167201254915/1201372982295248/f
=> Improved Appointments report to Differentiate Appointments at different Locations of ART Clinic

omod/pom.xml
https://talk.openmrs.org/t/most-poms-configured-to-include-api-artifacts-twice-in-the-pom/35257
https://app.asana.com/0/1133167201254913/1201445963728403/f
=> Fix inclusion of API resources twice in the pom 

api/src/main/java/org/openmrs/module/ugandaemrreports/definition/dataset/definition/rest/AppointmentDatasetDefinition.java, api/src/main/java/org/openmrs/module/ugandaemrreports/definition/dataset/evaluator/rest/AppointmentDatasetEvaluator.java, omod/pom.xml, omod/src/main/java/org/openmrs/module/ugandaemrreports/web/controller/UgandaEMRReportsResourceController.java, omod/src/main/java/org/openmrs/module/ugandaemrreports/web/resources/DataEvaluatorRestController.java, pom.xml
https://metsprogramme.atlassian.net/browse/U4X-135
=> Rest Api end point for dataset definitions

api/src/main/java/org/openmrs/module/ugandaemrreports/api/UgandaEMRReportsService.java, api/src/main/java/org/openmrs/module/ugandaemrreports/api/db/hibernate/HibernateUgandaEMRReportsDAO.java, api/src/main/java/org/openmrs/module/ugandaemrreports/api/impl/UgandaEMRReportsServiceImpl.java, api/src/main/java/org/openmrs/module/ugandaemrreports/model/Dashboard.java, api/src/main/java/org/openmrs/module/ugandaemrreports/model/DashboardReportObject.java, api/src/main/resources/liquibase.xml, api/src/main/resources/moduleApplicationContext.xml, omod/src/main/java/org/openmrs/module/ugandaemrreports/web/resources/DashboardReportObjectResource.java, omod/src/main/java/org/openmrs/module/ugandaemrreports/web/resources/DashboardResource.java
End points for dashboards and report objects .  create, and retrieve 
{{serverurl}}/openmrs/ws/rest/v1/dashboard
{{serverurl}}/openmrs/ws/rest/v1/dashboardReport
=> Added Report Object and Dashboard with their endpoints 

omod/src/main/java/org/openmrs/module/ugandaemrreports/web/resources/DataDefinitionRestController.java, omod/src/main/java/org/openmrs/module/ugandaemrreports/web/resources/EncounterTypeConceptsRestController.java, omod/src/main/java/org/openmrs/module/ugandaemrreports/web/resources/mapper/ConceptMapper.java
This PR ensure all data elements passed for reports are returned even if they have empty values 
Also added type attribute to concepts used by certain encounter
=> Return Empty Values For DataSet Built For Dynamic Reporting

api/src/main/java/org/openmrs/module/ugandaemrreports/model/Dashboard.java, api/src/main/java/org/openmrs/module/ugandaemrreports/model/DashboardReportObject.java, api/src/main/resources/liquibase.xml, omod/src/main/java/org/openmrs/module/ugandaemrreports/web/resources/DashboardResource.java
dashboard  post body sample 
`{"name":"HTS9",
"items":["9495a1ba-0b83-44bd-b289-910dcf7f487c","6c089c32-a6f1-49a5-8dc0-ef5c87771236"]
}`
GET return sample
`{
"uuid": "ae85e6f4-3b3d-4c30-9904-d575e491a05d",
"name": "HTS1",
"description": null,
"items": [
{
"uuid": "9495a1ba-0b83-44bd-b289-910dcf7f487c",
"name": "test example name",
"description": "test description 1",
"type": "bar Chart",
"columns": "Age, Party, province",
"rows": "Gender",
"aggregator": null,
"report_request_object": "{my body}",
"links": [
{
"rel": "self",
"uri": "http://localhost:8080/openmrs/ws/rest/v1/dashboardReport/9495a1ba-0b83-44bd-b289-910dcf7f487c",
"resourceAlias": "dashboardReport"
}
],
"resourceVersion": "1.8"
},
{
"uuid": "6c089c32-a6f1-49a5-8dc0-ef5c87771236",
"name": "test example name",
"description": …
=> Retrieve and add reports to dashboard easily 

omod/src/main/java/org/openmrs/module/ugandaemrreports/web/resources/ProcessAndDownloadReportController.java
endpoint example 
/ws/rest/v1/ugandaemrreports/reportDownload?startDate=2023-01-01&endDate=2023-03-30&uuid=5718901d-3dae-4a0d-9847-df345bf0de39
=> Download report end point 

omod/src/main/java/org/openmrs/module/ugandaemrreports/web/resources/PatientViralLoad_IITRestController.java
Endpoint : 
endpoint supports both patient id and patient uuid 
http://localhost:8080/openmrs/ws/rest/v1/ugandaemrreports/iit?id=c7a189dd-3267-4999-ab06-e35c2b18bc2a
http://localhost:8080/openmrs/ws/rest/v1/ugandaemrreports/iit?id=1234
=> VIRAL LOAD AND IIT END POINT

api/src/main/java/org/openmrs/module/ugandaemrreports/reports/SetUpRecencyHTSClientCardDataExportReport2019.java
https://metsprogramme.atlassian.net/browse/U4X-750
=> U4X-750: Add county, parish and village field to recency data extract

api/src/main/java/org/openmrs/module/ugandaemrreports/api/UgandaEMRReportsService.java, api/src/main/java/org/openmrs/module/ugandaemrreports/api/db/UgandaEMRReportsDAO.java, api/src/main/java/org/openmrs/module/ugandaemrreports/api/db/hibernate/HibernateUgandaEMRReportsDAO.java, api/src/main/java/org/openmrs/module/ugandaemrreports/api/impl/UgandaEMRReportsServiceImpl.java, omod/src/main/java/org/openmrs/module/ugandaemrreports/web/resources/ConditionsConceptsRestController.java, omod/src/main/java/org/openmrs/module/ugandaemrreports/web/resources/DataDefinitionRestController.java, omod/src/main/java/org/openmrs/module/ugandaemrreports/web/resources/DrugIndicationsRestController.java, omod/src/main/java/org/openmrs/module/ugandaemrreports/web/resources/Helper.java
https://metsprogramme.atlassian.net/browse/U4X-587
=> U4X-587:Data Export added export of Drug Orders

api/src/main/resources/moduleApplicationContext.xml, omod/pom.xml
https://metsprogramme.atlassian.net/browse/U4X-833
=> U4X-833: Correcting dependency issues in ugandaemr reports
